FROM node:lts as base
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
ENV HOST=0.0.0.0


FROM base as development
ENV PORT=3000
EXPOSE 3000
CMD yarn dev


FROM base as build
RUN yarn generate
RUN yarn build


FROM base as production
ENV PORT=80
EXPOSE 80
CMD yarn start
