FROM node:lts-alpine as development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000
CMD [ "npm" ,"run", "dev" ]

FROM node:lts as production-server
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ENV HOST=0.0.0.0
ENV PORT=80

RUN npm run build
CMD [ "npm", "run", "start" ]
