FROM node:lts-alpine as development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000
CMD [ "npm" ,"run", "dev" ]

FROM node:lts as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ENV HOST=0.0.0.0
ENV PORT=3000

RUN npm run build

FROM nginx:stable-alpine as production-server
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
