version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    depends_on:
      - frontend
      - backend
      - adminer
    container_name: feeby-traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    container_name: feeby-backend-dev
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend/app:/app
    ports:
      - 5678:5678
    environment:
      - BASE_CANVAS_URL=https://canvas.lucabergman.nl
      - BASE_APP_URL=http://localhost
      - JWT_ALGORITHM=HS256
      - DATABASE_URL=db
    secrets:
      - CANVAS_CLIENT_ID
      - CANVAS_CLIENT_SECRET
      - CANVAS_DEVELOPER_KEY
      - CANVAS_DEVELOPER_KEY_ID
      - JWT_SECRET
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    labels:
      traefik.enable: true
      traefik.http.routers.backend.rule: Host(`127.0.0.1`) || Host(`localhost`) && PathPrefix(`/api/v1`)
      traefik.http.services.backend.loadbalancer.server.port: 80
      traefik.http.middlewares.backendpathstrip.stripprefix.prefixes: /api/v1
      traefik.http.routers.backend.middlewares: backendpathstrip@docker

  frontend:
    container_name: feeby-frontend-dev
    depends_on:
      - backend
    build:
      context: ./frontend
      target: development
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`localhost`) || Host(`127.0.0.1`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: 3000


  db:
    container_name: feeby-database-dev
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    container_name: feeby-redis-dev
    image: redis

  adminer:
    container_name: feeby-adminer-dev
    depends_on:
      - db
    image: adminer
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.rule: Host(`adminer.localhost`)
      traefik.http.routers.adminer.entrypoints: web
      traefik.http.services.adminer.loadbalancer.server.port: 8080


secrets:
  CANVAS_CLIENT_ID:
    file: CANVAS_CLIENT_ID.txt
  CANVAS_CLIENT_SECRET:
    file: CANVAS_CLIENT_SECRET.txt
  CANVAS_DEVELOPER_KEY:
    file: CANVAS_DEVELOPER_KEY.txt
  CANVAS_DEVELOPER_KEY_ID:
    file: CANVAS_DEVELOPER_KEY_ID.txt
  JWT_SECRET:
    file: JWT_SECRET.txt
  POSTGRES_PASSWORD:
    file: POSTGRES_PASSWORD.txt
  POSTGRES_USER:
    file: POSTGRES_USER.txt
    